### ISSUE TITLE
New Design Tiles

### ISSUE THREAD

**Issue by martinheppner** [bahnzumberg/zuugle-suchseite#357]
We have a new design defined in Figma for the tiles on our startpage https://www.zuugle.at/?city=wien and the resultpage https://www.zuugle.at/suche?city=wien 

We want the new design to be implemented on both pages (using one function).

What do I mean with **"Tile"**? This: 
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/c65fc8d4-28dc-47ad-a6f9-462e5d7df086)

Mobile and desktop view should use the new tile design and look like this:

**Mobile View**
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/d7ea1b64-aa27-41de-9154-2d29b1d93a82)

**Desktop View**
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/70be488b-f05c-42bb-be93-bba6c51a3091)

Howto contribute via pull request: https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

- Go to https://github.com/bahnzumberg/zuugle-suchseite
- nvm use
- npm install
- npm run start-remote-api

The logos of the providers are in /public/logos as svg files. If a file with the name of the provider as the filename can be found, it should be shown. Otherwise the fallback.svg is shown.
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/f1051575-e537-4674-a319-aadc9fdea259)

**Figma Mobile & Assets:** https://www.figma.com/design/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?node-id=0-1&t=VbLfpfQGZMUwmkVS-0
**Figma Desktop:** https://www.figma.com/design/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?node-id=858-13723&t=NC3nuqbhk6T3mk6K-0

**Comment by martinheppner** [comment]
The GitHub repository you need is https://github.com/bahnzumberg/zuugle-suchseite

**Comment by martinheppner** [comment]
The relevant file should be https://github.com/bahnzumberg/zuugle-suchseite/blob/uat/src/components/TourCard.js

**Comment by martinheppner** [comment]
The logos are not implemented correctly. Above - in the initial demand - the goal has been described as "_The logos of the providers are in /public/logos as svg files. If a file with the name of the provider as the filename can be found, it should be shown. Otherwise the fallback.svg is shown._"

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/cfad6297-9912-45e0-bb6e-21e45be7dd5a)

**Comment by martinheppner** [comment]
- [ ] Startpage lower part 

How it should look like: https://www.figma.com/proto/qM4hoaxmGrrEEuTv4lL2lD/zuugle-redesign-2023-v3.0?node-id=110-5679&t=GqTXRrhAYI9cvRUm-0&scaling=scale-down&content-scaling=fixed&page-id=110%3A5678&starting-point-node-id=110%3A5679

How it looks now:
![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/562ace67-0de2-4348-81be-c5f5ce58f196)

**Comment by martinheppner** [comment]
- [ ]  Footer 

Please leave the footer as it was before. This ticket is called "New Design Tiles". The footer was already ok before.

**Comment by martinheppner** [comment]
- [ ] Remove Ad from Resultspage

It should always be 9 tiles to load on the page https://www2.zuugle.at/suche?city=wien. Now with the Ad, there is a 4th line, with a single tile. To change that, it would be too much effort. So please remove the ad from the Resultspage https://www2.zuugle.at/suche?city=wien

**Comment by uzair-shakeel** [comment]
Fixed all the things. Please review it.
Thanks.

**Comment by martinheppner** [comment]
We added all missing functionality and tested the page.

Everything is finished. Two tiny taks are open:

1. The round cornbers on top are still missing. On both sites: On https://www2.zuugle.at/?city=wien and on https://www2.zuugle.at/suche?city=wien
2. The page https://www2.zuugle.at/?city=wien is not centered and the columns have more space, the tiles are wider, than on the second. It should be like on https://www2.zuugle.at/suche?city=wien See images below.

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/6b84c200-413c-4e02-9834-0a56dd9b4ff7)

![Image](https://github.com/bahnzumberg/zuugle-suchseite/assets/105971399/ad67884f-1532-4dce-8b55-957cc22a0915)
